BEGIN
    UPDATE [test-portaldb].[dbo].[yng_dim_sku_data] SET fz_top_limit = 35.36, fz_bottom_limit = 35.1, fz_std = 35.23, extruder_exit_gum_temp_top_limit = 50.95, extruder_exit_gum_temp_bottom_limit = 49.03 WHERE sku_name = 'FVPP';
    UPDATE [test-portaldb].[dbo].[yng_dim_sku_data] SET fz_top_limit = 35.36, fz_bottom_limit = 35.1, fz_std = 35.23, extruder_exit_gum_temp_top_limit = 50.74, extruder_exit_gum_temp_bottom_limit = 48.69 WHERE sku_name = 'FVSS';
    UPDATE [test-portaldb].[dbo].[yng_dim_sku_data] SET fz_top_limit = 35.36, fz_bottom_limit = 35.1, fz_std = 35.23, extruder_exit_gum_temp_top_limit = 51.42, extruder_exit_gum_temp_bottom_limit = 49.04 WHERE sku_name = 'FVWM';
    UPDATE [test-portaldb].[dbo].[yng_dim_sku_data] SET fz_top_limit = 35.36, fz_bottom_limit = 35.1, fz_std = 35.23, extruder_exit_gum_temp_top_limit = 51.01, extruder_exit_gum_temp_bottom_limit = 49.53 WHERE sku_name = 'FVBB';
    UPDATE [test-portaldb].[dbo].[yng_dim_sku_data] SET fz_top_limit = 35.36, fz_bottom_limit = 35.1, fz_std = 35.23, extruder_exit_gum_temp_top_limit = 48.78, extruder_exit_gum_temp_bottom_limit = 45.89 WHERE sku_name = 'DMRC';
    UPDATE [test-portaldb].[dbo].[yng_dim_sku_data] SET fz_top_limit = 35.36, fz_bottom_limit = 35.1, fz_std = 35.23, extruder_exit_gum_temp_top_limit = 51.02, extruder_exit_gum_temp_bottom_limit = 48.58 WHERE sku_name = 'EXSM';
    UPDATE [test-portaldb].[dbo].[yng_dim_sku_data] SET fz_top_limit = 35.36, fz_bottom_limit = 35.1, fz_std = 35.23, extruder_exit_gum_temp_top_limit = 48.16, extruder_exit_gum_temp_bottom_limit = 46.67 WHERE sku_name = 'DMPY';
    UPDATE [test-portaldb].[dbo].[yng_dim_sku_data] SET fz_top_limit = 35.36, fz_bottom_limit = 35.1, fz_std = 35.23, extruder_exit_gum_temp_top_limit = 49.62, extruder_exit_gum_temp_bottom_limit = 47.93 WHERE sku_name = 'DMLM';
    UPDATE [test-portaldb].[dbo].[yng_dim_sku_data] SET fz_top_limit = 35.36, fz_bottom_limit = 35.1, fz_std = 35.23, extruder_exit_gum_temp_top_limit = 51.41, extruder_exit_gum_temp_bottom_limit = 49.44 WHERE sku_name = 'EXCW';
    UPDATE [test-portaldb].[dbo].[yng_dim_sku_data] SET fz_top_limit = 35.36, fz_bottom_limit = 35.1, fz_std = 35.23, extruder_exit_gum_temp_top_limit = 51.38, extruder_exit_gum_temp_bottom_limit = 49.19 WHERE sku_name = 'EXTP';
    UPDATE [test-portaldb].[dbo].[yng_dim_sku_data] SET fz_top_limit = 35.36, fz_bottom_limit = 35.1, fz_std = 35.23, extruder_exit_gum_temp_top_limit = 51.55, extruder_exit_gum_temp_bottom_limit = 48.17 WHERE sku_name = 'EBB';
    UPDATE [test-portaldb].[dbo].[yng_dim_sku_data] SET fz_top_limit = 35.36, fz_bottom_limit = 35.1, fz_std = 35.23, extruder_exit_gum_temp_top_limit = 48.54, extruder_exit_gum_temp_bottom_limit = 45.07 WHERE sku_name = 'WSP';
    UPDATE [test-portaldb].[dbo].[yng_dim_sku_data] SET fz_top_limit = 71.0, fz_bottom_limit = 70.2, fz_std = 70.75, extruder_exit_gum_temp_top_limit = 51.45, extruder_exit_gum_temp_bottom_limit = 49.72 WHERE sku_name = 'RPCM';
    UPDATE [test-portaldb].[dbo].[yng_dim_sku_data] SET fz_top_limit = 35.36, fz_bottom_limit = 35.1, fz_std = 35.23, extruder_exit_gum_temp_top_limit = 52.29, extruder_exit_gum_temp_bottom_limit = 51.76 WHERE sku_name = 'AUWM';
    UPDATE [test-portaldb].[dbo].[yng_dim_sku_data] SET fz_top_limit = 35.36, fz_bottom_limit = 35.1, fz_std = 35.23, extruder_exit_gum_temp_top_limit = 48.04, extruder_exit_gum_temp_bottom_limit = 46.37 WHERE sku_name = 'DMRR';
    UPDATE [test-portaldb].[dbo].[yng_dim_sku_data] SET fz_top_limit = 35.36, fz_bottom_limit = 35.1, fz_std = 35.23, extruder_exit_gum_temp_top_limit = 50.21, extruder_exit_gum_temp_bottom_limit = 48.22 WHERE sku_name = 'DMRJ';
    UPDATE [test-portaldb].[dbo].[yng_dim_sku_data] SET fz_top_limit = 35.36, fz_bottom_limit = 35.1, fz_std = 35.23, extruder_exit_gum_temp_top_limit = 51.05, extruder_exit_gum_temp_bottom_limit = 48.77 WHERE sku_name = 'EXPP';
    UPDATE [test-portaldb].[dbo].[yng_dim_sku_data] SET fz_top_limit = 35.36, fz_bottom_limit = 35.1, fz_std = 35.23, extruder_exit_gum_temp_top_limit = 47.57, extruder_exit_gum_temp_bottom_limit = 46.08 WHERE sku_name = 'DMPE';
    UPDATE [test-portaldb].[dbo].[yng_dim_sku_data] SET fz_top_limit = 71.0, fz_bottom_limit = 70.2, fz_std = 70.75, extruder_exit_gum_temp_top_limit = 52.0, extruder_exit_gum_temp_bottom_limit = 46.0 WHERE sku_name = 'RPSY';
    UPDATE [test-portaldb].[dbo].[yng_dim_sku_data] SET fz_top_limit = 71.0, fz_bottom_limit = 70.2, fz_std = 70.75, extruder_exit_gum_temp_top_limit = 51.44, extruder_exit_gum_temp_bottom_limit = 48.22 WHERE sku_name = 'RPWP';
    UPDATE [test-portaldb].[dbo].[yng_dim_sku_data] SET fz_top_limit = 71.0, fz_bottom_limit = 70.2, fz_std = 70.75, extruder_exit_gum_temp_top_limit = 52.0, extruder_exit_gum_temp_bottom_limit = 46.0 WHERE sku_name = 'DMLG';
    UPDATE [test-portaldb].[dbo].[yng_dim_sku_data] SET fz_top_limit = 35.36, fz_bottom_limit = 35.1, fz_std = 35.23, extruder_exit_gum_temp_top_limit = 49.12, extruder_exit_gum_temp_bottom_limit = 47.72 WHERE sku_name = 'DMRM';
END