SELECT [id]
      ,[sku]
      ,[extruder_exit_gum_temp]
      ,[n1_roller_gap]
      ,[n2_roller_gap]
      ,[n3_roller_gap]
      ,[forming_roller_gap]
      ,[extruder_temperature_up]
      ,[extruder_temperature_up_sv]
      ,[cross_cutter_speed]
      ,[cross_cutter_speed_sv]
      ,[data_time]
      ,[weight_ts]
      ,[shift]
      ,[actual_weight]
      ,[sr_recommend_1_roller_gap]
      ,[sr_recommend_2_roller_gap]
      ,[sr_recommend_3_roller_gap]
      ,[sr_recommend_forming_roller_gap]
      ,[sr_recommend_extruder_temperature_up]
      ,[sr_recommend_cross_cutter_speed]
      ,[diff_recommend_1_roller_gap]
      ,[diff_recommend_2_roller_gap]
      ,[diff_recommend_3_roller_gap]
      ,[diff_recommend_forming_roller_gap]
      ,[diff_recommend_extruder_temperature_up]
      ,[diff_recommend_cross_cutter_speed]
      ,[predicted_weight]
      ,[operator_status]
      ,[operator_reason]
      ,[write_back_status]
      ,[write_back_type]
      ,[recommend_weight_data_id]
      ,[create_by]
      ,[update_by]
      ,[create_time]
      ,[update_time]
  FROM [test-portaldb].[dbo].[yng_recommend_weight_data_log]
  WHERE [is_change] = '1'
	AND [data_time] > '2024-10-29 13:00:06'
